
  - name: kernel.sysrq config
    sysctl:
      name: kernel.sysrq
      value: 1
      sysctl_set: yes
      state: present
      reload: yes

  - name: kernel.core_pattern config
    sysctl:
      name: kernel.core_pattern
      value: core.%e
      sysctl_set: yes
      state: present
      reload: yes

  - name: kernel.sem config
    sysctl:
      name: kernel.sem
      value: 256 32000 100 142
      sysctl_set: yes
      state: present
      reload: yes

  - name: kernel.shmmni config
    sysctl:
      name: kernel.shmmni
      value: 4096
      sysctl_set: yes
      state: present
      reload: yes

  - name: kernel.msgmni config
    sysctl:
      name: kernel.msgmni
      value: 2878
      sysctl_set: yes
      state: present
      reload: yes

  - name: fs.file-max config
    sysctl:
      name: fs.file-max
      value: 52458632
      sysctl_set: yes
      state: present
      reload: yes

  - name: fs.aio-max-nr config
    sysctl:
      name: fs.aio-max-nr
      value: 1048576
      sysctl_set: yes
      state: present
      reload: yes

  - name: net.core.somaxconn config
    sysctl:
      name: net.core.somaxconn
      value: 8192
      sysctl_set: yes
      state: present
      reload: yes

  - name: net.ipv4.tcp_max_syn_backlog config
    sysctl:
      name: net.ipv4.tcp_max_syn_backlog
      value: 8192
      sysctl_set: yes
      state: present
      reload: yes

  - name: net.core.netdev_max_backlog config
    sysctl:
      name: net.core.netdev_max_backlog
      value: 100000
      sysctl_set: yes
      state: present
      reload: yes

  - name: net.core.rmem_default config
    sysctl:
      name: net.core.rmem_default
      value: 262144
      sysctl_set: yes
      state: present
      reload: yes

  - name: net.core.rmem_max config
    sysctl:
      name: net.core.rmem_max
      value: 4194304
      sysctl_set: yes
      state: present
      reload: yes

  - name: net.core.wmem_default config
    sysctl:
      name: net.core.wmem_default
      value: 262144
      sysctl_set: yes
      state: present
      reload: yes

  - name: net.core.wmem_max config
    sysctl:
      name: net.core.wmem_max
      value: 4194304
      sysctl_set: yes
      state: present
      reload: yes

  - name: net.ipv4.tcp_wmem config
    sysctl:
      name: net.ipv4.tcp_wmem
      value: 4096 65536 4194304
      sysctl_set: yes
      state: present
      reload: yes

  - name: net.ipv4.tcp_rmem config
    sysctl:
      name: net.ipv4.tcp_rmem
      value: 4096 87380 6291456
      sysctl_set: yes
      state: present
      reload: yes

  - name: net.ipv4.tcp_keepalive_time config
    sysctl:
      name: net.ipv4.tcp_keepalive_time
      value: 600
      sysctl_set: yes
      state: present
      reload: yes

  - name: net.ipv4.tcp_keepalive_intvl config
    sysctl:
      name: net.ipv4.tcp_keepalive_intvl
      value: 30
      sysctl_set: yes
      state: present
      reload: yes

  - name: net.ipv4.tcp_keepalive_probes
    sysctl:
      name: net.ipv4.tcp_keepalive_probes
      value: 5
      sysctl_set: yes
      state: present
      reload: yes

  - name: net.ipv4.tcp_fin_timeout
    sysctl:
      name: net.ipv4.tcp_fin_timeout
      value: 15
      sysctl_set: yes
      state: present
      reload: yes

  - name: net.ipv4.tcp_moderate_rcvbuf config
    sysctl:
      name: net.ipv4.tcp_moderate_rcvbuf
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
  
  - name: net.ipv4.tcp_rfc1337 config
    sysctl:
      name: net.ipv4.tcp_rfc1337
      value: 1
      sysctl_set: yes
      state: present
      reload: yes

  - name: net.ipv4.ip_local_port_range config
    sysctl:
      name: net.ipv4.ip_local_port_range
      value: 10000 65000
      sysctl_set: yes
      state: present
      reload: yes

  - name: vm.dirty_background_ratio config
    sysctl:
      name: vm.dirty_background_ratio
      value: 3
      sysctl_set: yes
      state: present
      reload: yes

  - name: vm.dirty_ratio config
    sysctl:
      name: vm.dirty_ratio
      value: 15
      sysctl_set: yes
      state: present
      reload: yes

  - name: vm.dirty_expire_centisecs config
    sysctl:
      name: vm.dirty_expire_centisecs
      value: 500
      sysctl_set: yes
      state: present
      reload: yes

  - name: vm.dirty_writeback_centisecs config
    sysctl:
      name: vm.dirty_writeback_centisecs
      value: 100
      sysctl_set: yes
      state: present
      reload: yes

  - name: vm.vfs_cache_pressure config
    sysctl:
      name: vm.vfs_cache_pressure
      value: 5000
      sysctl_set: yes
      state: present
      reload: yes

  - name: vm.swappiness config
    sysctl:
      name: vm.swappiness
      value: 1
      sysctl_set: yes
      state: present
      reload: yes

