
  - name: copy pwquality.conf
    template:
      src: templates/pwquality.conf.j2
      dest: /etc/security/pwquality.conf
    ignore_errors: True

 
  - name: copy login.defs
    template:
      src: templates/login.defs.j2
      dest: /etc/login.defs
    ignore_errors: True


  - name: copy system-auth-ac
    template:
      src: templates/system-auth-ac.j2
      dest: /etc/pam.d/system-auth-ac
    ignore_errors: True

  - name: copy password-auth-ac
    template:
      src: templates/password-auth-ac.j2
      dest: /etc/pam.d/password-auth-ac
    ignore_errors: True

  - name: Check that the /root/.bash_history exists
    stat:
      path: /root/.bash_history
    register: stat_result 
 
  - name: .bash_history permissions
    file:
      path: /root/.bash_history
      owner: root
      group: root
      mode: 0640
    when: stat_result.stat.exists == True

  - name: Check that the /root/.cshrc exists
    stat:
      path: /root/.cshrc
    register: stat_result
 
  - name: .cshrc permissions
    file:
      path: /root/.cshrc
      owner: root
      group: root
      mode: 0640
    when: stat_result.stat.exists == True
  
  - name: Check that the /etc/rc.d/rc.local exists
    stat:
      path: /etc/rc.d/rc.local
    register: stat_result

  - name: rc.local  permissions
    file:
      path: /etc/rc.d/rc.local
      owner: root
      group: root
      mode: 0754
    when: stat_result.stat.exists == True

  - name: Check that the /etc/rc.d/rc exists
    stat:
      path: /etc/rc.d/rc
    register: stat_result
  
  - name: rc  permissions
    file:
      path: /etc/rc.d/rc
      owner: root
      group: root
      mode: 0754
    when: stat_result.stat.exists == True

  - name: Check that the /etc/rc.d/rc.sysinit exists
    stat:
      path: /etc/rc.d/rc.sysinit
    register: stat_result

  - name: rc.sysinit  permissions
    file:
      path: /etc/rc.d/rc.sysinit
      owner: root
      group: root
      mode: 0754
    when: stat_result.stat.exists == True

  - name: Check that the /etc/init.d exists
    stat:
      path: /etc/init.d
    register: stat_result

  - name: init.d  permissions
    file:
      path: /etc/rc.d/init.d
      owner: root
      group: root
      mode: 0754
    when: stat_result.stat.exists == True

  - name: Check that the /etc/init.d/* exists
    stat:
      path: /etc/init.d/*
    register: stat_result

  - name: init.d/*  permissions
    file:
      path: /etc/init.d/*
      owner: root
      group: root
      mode: 0754
      recurse: yes
    when: stat_result.stat.exists == True

